name_of_the_user = input("Enter your name\n")
length_of_the_name = len(name_of_the_user)
print(type("Number of letters in your name: "))
print(type(length_of_the_name))
print("Number of letters in your name: "+ str(length_of_the_name))